#!/usr/bin/env sh

if [ "$1" != "" ]; then
   OPTION=$1
else
   OPTION="--help"
fi

if [ "$OPTION" = "--version" ]; then
   echo "Dinit-tree version 0.1pre."
   exit 0
fi

if [ "$OPTION" = "--help" ]; then
   echo "dinit-tree: simple tool to know about current system dinit's depends system"
   echo " --help                       display (this) help"
   echo " --version                    display version"
   echo " <path/to/service>, <'path/to/service_directory/*'>"
   echo "                              path to dinit service or dinit service(s) directory"
   echo " NOTE: if you want search a directory; path must be writes between ''"
   echo " otherwise just one file proceseed."
   exit 0
fi

/usr/bin/env awk '{
if(FNR==1) {print "\nservice :",FILENAME};

if($1=="depends-on"||$1=="depends-ms"||$1=="waits-for"||$1=="after"||$1=="before") {
   printf "\t  %s :\t%s\n",$1,$3}
}' $OPTION
